name: Rust

on:
  push:
    branches: [ bevy ]
  pull_request:
    branches: [ bevy ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install LLD
      run: sudo apt-get install lld
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
